
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=America/Vancouver
    username: yong
    password: yong1234
  
  jap:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardlmpl
      user-new-id-generator-mapping: false
    show-sql: true
    properties:
      hibernate.format_sql: true
    
  jackson:
    serialization:
      fail-on-empty-beans: false